services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - '5000:5000'
    command: tail -f /dev/null
    env_file:
      - .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=auth-service
    volumes:
      - .:/app
    restart: always
    networks:
      - authentication-net
    depends_on:
      - database
      - cache

  database:
    container_name: postgres
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: root
      POSTGRES_DB: auth
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
    networks:
      - authentication-net

  cache:
    container_name: redis
    image: redis:7.4.6
    hostname: redis
    restart: always
    volumes:
      - v-cache:/data
    ports:
      - '6379:6379'
    networks:
      - authentication-net

  cache-ui:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '8081:8081'
    depends_on:
      - cache
    networks:
      - authentication-net
  
  # OBSERVABILITY
  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: signoz-clickhouse
    ports:
      - "9000:9000" # Native protocol
      - "9090:9090" # GUI
    volumes:
      - v-clickhouse:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - authentication-net

  signoz:
    image: signoz/signoz-community:latest
    container_name: signoz-standalone
    deploy:
      resources:
        limits:
          memory: 1G
    user: "root"
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8080:8080" # GUI
      - "4317:4317" # gRPC Ingestion
      - "4318:4318" # HTTP Ingestion
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - SIGNOZ_CLICKHOUSE_ADDRESS=clickhouse:9000
      - ALERTMANAGER_API_PREFIX=http://signoz:8080/api/v1/alerts
      - TELEMETRY_STORE_ADDRESS=clickhouse:9000
      - GODEBUG=netdns=go
      - CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_TOKENIZER_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwibm93IjoxNzc2OTE4NDk4NjA0LCJleHAiOjE3NzY5MjIwOTgsImlhdCI6MTc3NjkxODQ5OH0.ishNqa2vNw7CemmkKNAop4MDViSstIhnJ2ZsUCtAiAs
      - SIGNOZ_USER_ROOT_ENABLED=true
      - SIGNOZ_USER_ROOT_EMAIL=admin@authplus.com
      - SIGNOZ_USER_ROOT_PASSWORD=AuthPlus123!
      - SIGNOZ_USER_ROOT_ORG_NAME=default
    volumes:
      - v-signoz:/var/lib/signoz
    networks:
      - authentication-net

  otel-collector:
    image: signoz/signoz-otel-collector:latest
    container_name: signoz-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8888:8888"
    depends_on:
      - signoz
    networks:
      - authentication-net

networks:
  authentication-net:
    driver: bridge

volumes:
  v-database:
    driver: local
  v-cache:
    driver: local
  v-signoz:
    driver: local
  v-clickhouse:
    driver: local