services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - '5000:5000'
    command: npm run dev
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - CACHE_URL=cache
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_SERVICE_NAME=auth-service
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - authentication-net
    depends_on:
      - database
      - cache

  database:
    image: postgres:17.6
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: root
      POSTGRES_DB: auth
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d auth']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - v-database:/var/lib/postgresql/data
    networks:
      - authentication-net

  cache:
    image: valkey/valkey:7.2-alpine3.23
    restart: always
    volumes:
      - v-cache:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 1s
      timeout: 1s
      retries: 30
    networks:
      - authentication-net

  cache-ui:
    image: valkey/valkey-admin:1.0.2
    container_name: valkey-admin
    restart: always
    environment:
      - VALKEY_HOST=cache
      - VALKEY_PORT=6379
    ports:
      - '8081:8080'
    depends_on:
      - cache
    networks:
      - authentication-net

networks:
  authentication-net:
    driver: bridge

volumes:
  v-database:
    driver: local
  v-cache:
    driver: local
  v-clickhouse:
    driver: local
