receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  # SigNoz specific native ClickHouse exporters using separate config keys
  clickhousetraces:
    datasource: "tcp://default:your_secure_password@clickhouse:9000/signoz_traces?create_database_if_not_exists=true"
  
  signozclickhousemetrics:
    dsn: "tcp://default:your_secure_password@clickhouse:9000/signoz_metrics?create_database_if_not_exists=true"
  
  clickhouselogsexporter:
    dsn: "tcp://default:your_secure_password@clickhouse:9000/signoz_logs?create_database_if_not_exists=true"
    
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [signozclickhousemetrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouselogsexporter, debug]